<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260324083420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add User entity for JWT auth + settled column on Invoice';
    }

    public function up(Schema $schema): void
    {
        // Table User pour l'authentification JWT
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');

        // Colonne settled sur Invoice (facture réglée ou non)
        $this->addSql('ALTER TABLE invoice ADD settled BOOLEAN NOT NULL DEFAULT false');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE invoice DROP COLUMN settled');
    }
}
