<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260306140409 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, price INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE attendee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, deposit DOUBLE PRECISION NOT NULL, breakfast BOOLEAN NOT NULL, hotel_id INT DEFAULT NULL, organization_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1150D5673243BB18 ON attendee (hotel_id)');
        $this->addSql('CREATE INDEX IDX_1150D56732C8A3DE ON attendee (organization_id)');
        $this->addSql('CREATE TABLE attendee_session (attendee_id INT NOT NULL, session_id INT NOT NULL, PRIMARY KEY (attendee_id, session_id))');
        $this->addSql('CREATE INDEX IDX_D6D7072CBCFD782A ON attendee_session (attendee_id)');
        $this->addSql('CREATE INDEX IDX_D6D7072C613FECDF ON attendee_session (session_id)');
        $this->addSql('CREATE TABLE attendee_activity (attendee_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY (attendee_id, activity_id))');
        $this->addSql('CREATE INDEX IDX_1F14E0A6BCFD782A ON attendee_activity (attendee_id)');
        $this->addSql('CREATE INDEX IDX_1F14E0A681C06096 ON attendee_activity (activity_id)');
        $this->addSql('CREATE TABLE hotel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, night_price DOUBLE PRECISION NOT NULL, breakfast_price DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE invoice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total_amount DOUBLE PRECISION NOT NULL, print BOOLEAN NOT NULL, attendee_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90651744BCFD782A ON invoice (attendee_id)');
        $this->addSql('CREATE TABLE payer_organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, invoice_id INT DEFAULT NULL, organization_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D28840D2989F1FD ON payment (invoice_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D32C8A3DE ON payment (organization_id)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_half_days INT NOT NULL, price INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE attendee ADD CONSTRAINT FK_1150D5673243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id)');
        $this->addSql('ALTER TABLE attendee ADD CONSTRAINT FK_1150D56732C8A3DE FOREIGN KEY (organization_id) REFERENCES payer_organization (id)');
        $this->addSql('ALTER TABLE attendee_session ADD CONSTRAINT FK_D6D7072CBCFD782A FOREIGN KEY (attendee_id) REFERENCES attendee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE attendee_session ADD CONSTRAINT FK_D6D7072C613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE attendee_activity ADD CONSTRAINT FK_1F14E0A6BCFD782A FOREIGN KEY (attendee_id) REFERENCES attendee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE attendee_activity ADD CONSTRAINT FK_1F14E0A681C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744BCFD782A FOREIGN KEY (attendee_id) REFERENCES attendee (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D32C8A3DE FOREIGN KEY (organization_id) REFERENCES payer_organization (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attendee DROP CONSTRAINT FK_1150D5673243BB18');
        $this->addSql('ALTER TABLE attendee DROP CONSTRAINT FK_1150D56732C8A3DE');
        $this->addSql('ALTER TABLE attendee_session DROP CONSTRAINT FK_D6D7072CBCFD782A');
        $this->addSql('ALTER TABLE attendee_session DROP CONSTRAINT FK_D6D7072C613FECDF');
        $this->addSql('ALTER TABLE attendee_activity DROP CONSTRAINT FK_1F14E0A6BCFD782A');
        $this->addSql('ALTER TABLE attendee_activity DROP CONSTRAINT FK_1F14E0A681C06096');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_90651744BCFD782A');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D2989F1FD');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D32C8A3DE');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE attendee');
        $this->addSql('DROP TABLE attendee_session');
        $this->addSql('DROP TABLE attendee_activity');
        $this->addSql('DROP TABLE hotel');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE payer_organization');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE session');
    }
}
